#name: "goods-web"
#port: 8021
#
#user_srv:
#  host: 192.168.1.101
#  port: 50051
#  name: user-srv
#
#jwt:
#  signingKey: 'lkOGRZIJLSZZD7Nr!0xJYf4uU44l81z%'
#
#sms:
#  apikey: 'LTAI5t6qhWgUURgQ5BZdzwCB'
#  apisecret: 'ju34xudfSMOXbTGwVWpVoSNhQIRR92'
#  expire: 6000
#
#redis:
#  host: 192.168.1.101
#  port: 6379
#
#consul:
#  host: 192.168.1.101
#  port: 8500


host: 192.168.1.101
port: 8848
namespaceId: 15fdf165-b5f4-4a9a-9402-0150e4bc774d
dataId: goods-web.json
group: dev